-- 口播爆了么：Supabase Auth、用户数据与扩展连接码
-- 幂等迁移：保留既有 profiles / payments 数据，可重复执行。

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists updated_at timestamptz not null default now();
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists identity text not null default '';
alter table public.profiles add column if not exists content_direction text not null default '';
alter table public.profiles add column if not exists target_audience text not null default '';
alter table public.profiles add column if not exists personal_story text not null default '';
alter table public.profiles add column if not exists speaking_style text not null default '真诚直接';
alter table public.profiles add column if not exists creator_dna jsonb not null default '{}'::jsonb;
alter table public.profiles add column if not exists voice_dna jsonb;
alter table public.profiles add column if not exists preferences jsonb not null default '{}'::jsonb;

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '未命名项目',
  status text not null default 'draft' check (status in ('draft', 'ready_to_shoot', 'filmed', 'published', 'archived')),
  source_type text not null default 'idea' check (source_type in ('idea', 'reference', 'extension', 'manual')),
  platform text,
  source_url text,
  source_data jsonb not null default '{}'::jsonb,
  evidence jsonb not null default '{}'::jsonb,
  analysis jsonb,
  input_data jsonb not null default '{}'::jsonb,
  script jsonb,
  project_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_user_updated_idx on public.projects(user_id, updated_at desc);

create table if not exists public.extension_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '默认浏览器',
  token_hash text not null unique,
  token_prefix text not null,
  expires_at timestamptz,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists extension_tokens_user_idx on public.extension_tokens(user_id, created_at desc);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  project_id uuid references public.projects(id) on delete set null,
  units integer not null default 1 check (units >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists usage_events_user_created_idx on public.usage_events(user_id, created_at desc);
create index if not exists usage_events_type_created_idx on public.usage_events(event_type, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at before update on public.projects
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email)
select id, email from auth.users
on conflict (id) do update set email = excluded.email;

alter table public.profiles enable row level security;
alter table public.projects enable row level security;
alter table public.extension_tokens enable row level security;
alter table public.usage_events enable row level security;

revoke all on table public.profiles, public.projects, public.extension_tokens, public.usage_events from anon;
grant select, insert, update on table public.profiles to authenticated;
grant select, insert, update, delete on table public.projects to authenticated;
grant select on table public.extension_tokens to authenticated;
grant select on table public.usage_events to authenticated;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

drop policy if exists "projects_select_own" on public.projects;
create policy "projects_select_own" on public.projects for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "projects_insert_own" on public.projects;
create policy "projects_insert_own" on public.projects for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists "projects_update_own" on public.projects;
create policy "projects_update_own" on public.projects for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "projects_delete_own" on public.projects;
create policy "projects_delete_own" on public.projects for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "extension_tokens_select_own" on public.extension_tokens;
create policy "extension_tokens_select_own" on public.extension_tokens for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "usage_events_select_own" on public.usage_events;
create policy "usage_events_select_own" on public.usage_events for select to authenticated using ((select auth.uid()) = user_id);

-- token_hash 和 usage_events 只允许可信服务端写入；service_role 自动绕过 RLS。

create or replace function public.create_extension_token(token_name text default '默认浏览器')
returns table (id uuid, token text, token_prefix text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := (select auth.uid());
  raw_token text := 'kb_' || encode(extensions.gen_random_bytes(24), 'hex');
  new_id uuid;
begin
  if current_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  insert into public.extension_tokens (user_id, name, token_hash, token_prefix)
  values (current_user_id, left(coalesce(nullif(token_name, ''), '默认浏览器'), 80), encode(extensions.digest(raw_token, 'sha256'), 'hex'), left(raw_token, 11))
  returning extension_tokens.id into new_id;
  return query select new_id, raw_token, left(raw_token, 11);
end;
$$;

create or replace function public.validate_extension_token(candidate_token text)
returns table (user_id uuid, token_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
begin
  return query
  update public.extension_tokens
  set last_used_at = now()
  where token_hash = encode(extensions.digest(candidate_token, 'sha256'), 'hex')
    and revoked_at is null
    and (expires_at is null or expires_at > now())
  returning extension_tokens.user_id, extension_tokens.id;
end;
$$;

revoke all on function public.create_extension_token(text) from public;
grant execute on function public.create_extension_token(text) to authenticated;
revoke all on function public.validate_extension_token(text) from public;
grant execute on function public.validate_extension_token(text) to anon, authenticated;
